### ISSUE TITLE
Android: Круглосуточный режим работы

### ISSUE THREAD

**Issue by Alosolid** [naviworld/Naviaddress-public#1]
Не возможно сделать круглосуточный режим работы на iOS. Для круглосуточного режима нужно устанавливать 00:00 - 23:59, а если указать как андроиде  с 00:00 до 00:00  "эпл" показывает всегда закрыто.
![03_ _ _](https://user-images.githubusercontent.com/32391322/31016811-e2476d6a-a52e-11e7-859a-09d2959408c6.jpg)

**Comment by suhan3z** [comment]
Так скрин с Android же снят?

**Comment by Alosolid** [comment]
да
