### ISSUE TITLE
Интернет ссылка на навиадрес в Китае открывается на русском языке

### ISSUE THREAD

**Issue by Alosolid** [naviworld/Naviaddress-public#2]
Навикарточка, переданная ссылкой https://naviaddress.com/7495/0001  по WeChat в Пекин (Китай) на андроид телефоне открывается на русском языке (должна на китайском). Список языков RU, EN или ZH вываливается , но выбрать их нельзя. VPN на телефоне не установлен.
![1](https://user-images.githubusercontent.com/32391322/31018435-c0dc62e2-a534-11e7-860b-104260ef7cab.jpg)
![2](https://user-images.githubusercontent.com/32391322/31018436-c0de3dce-a534-11e7-8431-10d675dffb26.jpg)

**Comment by suhan3z** [comment]
В курсе про эту ошибку, поправим в редизайне

**Comment by suhan3z** [comment]
Нэ это мобильная версия, а не приложение
